//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public Meeting()
        {
            this.Meeting_Attendees_Map = new HashSet<Meeting_Attendees_Map>();
        }
    
        public int MeetingId { get; set; }
        public string Subject { get; set; }
        public string Agenda { get; set; }
        public System.DateTime MDateTime { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<Meeting_Attendees_Map> Meeting_Attendees_Map { get; set; }
    }
}
